import { BaseAgent } from './base_agent.ts';
import type { AgentInput } from './types.ts';

export class CriticAgent extends BaseAgent {
  constructor(modelName: string = 'gemini-2.5-flash') {
    const systemPrompt = `
      You are an independent Quality Control Auditor. 
      Review the initial grade sheet generated by the Grader AI against the student's text, original exam form, and rubric.
      Verify:
      1. Is the math completely correct? (Sum up the deductions).
      2. Did the Grader misinterpret a diagram description or code snippet?
      Output a clean, final, verified evaluation report.
    `;
    super('Critic', modelName, systemPrompt);
  }

  public async run(input: AgentInput): Promise<string> {
    return "";
  }
}
