import { BaseAgent } from './base_agent.ts';
import type { AgentInput } from './types.ts';

export class CriticAgent extends BaseAgent {
  constructor(modelName: string = 'gemini-2.0-flash') {
    const systemPrompt = `
      You are an independent Quality Control Auditor. 
      Review the initial grade sheet generated by the Grader AI against the student's text and rubric.
      Verify:
      1. Is the math completely correct? (Sum up the deductions).
      2. Did the Grader misinterpret a diagram description or code snippet?
      Output a clean, final, verified evaluation report.
    `;
    super('Critic', modelName, systemPrompt);
  }

  public async run(input: AgentInput): Promise<string> {
    if (!input.extractedText || !input.rubric || !input.initialGrade) {
      throw new Error(`[${this.name}] Missing state parameters for quality review.`);
    }

    console.log(`🤖 [${this.name}] Cross-checking calculations using ${this.modelName}...`);

    const userMessage = `
      === STUDENT EXAM ===
      ${input.extractedText}

      === RUBRIC ===
      ${input.rubric}

      === INITIAL GRADE UNDER REVIEW ===
      ${input.initialGrade}
    `;

    const response = await this.ai.models.generateContent({
      model: this.modelName,
      contents: [
        { role: 'user', parts: [{ text: `${this.systemPrompt}\n\n${userMessage}` }] }
      ]
    });

    return response.text || 'Audit review failed.';
  }
}
